version: 2

updates:
  - package-ecosystem: pip
    directory: /api
    schedule: { interval: weekly }
    groups:
      python:
        update-types: [minor, patch]
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /frontend
    schedule: { interval: weekly }
    ignore:
      - dependency-name: "@types/node"
        update-types: [ "version-update:semver-major" ]
    groups:
      npm:
        update-types: [minor, patch]
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    groups:
      actions:
        update-types: [minor, patch]
        patterns: ["*"]

  - package-ecosystem: docker
    directories: [/api, /frontend]
    schedule: { interval: weekly }

  - package-ecosystem: docker-compose
    directory: /
    schedule: { interval: weekly }

  - package-ecosystem: terraform
    directory: /terraform
    schedule: { interval: weekly }