services:
  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
    command:
      - "--address=0.0.0.0"
      - "--port=5432"
      - "--auto-iam-authn"
      - "agile-vortex-508316-k6:us-central1:rainbow-roadbook-db"
    restart: unless-stopped

  api:
    build: ./api
    env_file: .env.prod
    environment:
      - DJANGO_SECRET_KEY
    depends_on:
      - cloud-sql-proxy
    ports:
      - "8000:8000"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - api