name: Build Prod
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-prod:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: google-github-actions/auth@v3.0.0
        with:
          workload_identity_provider: projects/523773459301/locations/global/workloadIdentityPools/rainbowroadbook-github/providers/rainbowroadbook-github-actions
          service_account: rainbowroadbook-ci@agile-vortex-508316-k6.iam.gserviceaccount.com
      - uses: google-github-actions/setup-gcloud@v3.0.1
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - run: docker build -t us-central1-docker.pkg.dev/agile-vortex-508316-k6/rainbowroadbook-images/api:${{ github.sha }} ./api
      - run: docker push us-central1-docker.pkg.dev/agile-vortex-508316-k6/rainbowroadbook-images/api:${{ github.sha }}
      - run: docker build -t us-central1-docker.pkg.dev/agile-vortex-508316-k6/rainbowroadbook-images/frontend:${{ github.sha }} ./frontend -f frontend/Dockerfile.prod
      - run: docker push us-central1-docker.pkg.dev/agile-vortex-508316-k6/rainbowroadbook-images/frontend:${{ github.sha }}